-- Create a project-specific database
CREATE DATABASE IF NOT EXISTS ADTECH_ANALYTICS;

-- Create schema for staging layer
CREATE SCHEMA IF NOT EXISTS ADTECH_ANALYTICS.STAGING;

--  create a file format for stage

CREATE OR REPLACE FILE FORMAT adtech_csv_gz_format
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '');

  --  create a stage

GET_DDL('TABLE', 'STAGING.STG_CM360_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_HINDHU_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_INMOBI_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_PUBMATIC_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_WEBMD_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_BINGADS_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_AVZU_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_DV360_RAW_DATA');
GET_DDL('TABLE', 'STAGING.FILE_UPLOAD_LOG');
GET_DDL('TABLE', 'STAGING.MONTHLY__SPENDS_AND_PACING');
GET_DDL('TABLE', 'STAGING.STG_CM360_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_MIQ_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_IAS_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_AMAZON_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_TOI_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_REMEZCLA_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_SHARETHROUGH_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_CRITEO_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_MAGNITE_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_PRISMA__PLANNED');
GET_DDL('TABLE', 'STAGING.STG_TTD_RAW_DATA');
GET_DDL('TABLE', 'STAGING.STG_YOUTUBE_RAW_DATA');