
CREATE OR REPLACE STAGE raw.AMAZON_STAGE;
CREATE OR REPLACE STAGE raw.AVZU_STAGE;
CREATE OR REPLACE STAGE raw.BINGADS_STAGE;
CREATE OR REPLACE STAGE raw.CM360_STAGE;
CREATE OR REPLACE STAGE raw.CRITEO_STAGE;
CREATE OR REPLACE STAGE raw.DV360_STAGE;
CREATE OR REPLACE STAGE raw.HINDHU_STAGE;
CREATE OR REPLACE STAGE raw.IAS_STAGE;
CREATE OR REPLACE STAGE raw.INMOBI_STAGE;
CREATE OR REPLACE STAGE raw.MAGNITE_STAGE;
CREATE OR REPLACE STAGE raw.MIQ_STAGE;
CREATE OR REPLACE STAGE raw.PUBMATIC_STAGE;
CREATE OR REPLACE STAGE raw.REMEZCLA_STAGE;
CREATE OR REPLACE STAGE raw.SHARETHROUGH_STAGe;
CREATE OR REPLACE STAGE raw.TOI_STAGE;
CREATE OR REPLACE STAGE raw.TTD_STAGE;
CREATE OR REPLACE STAGE raw.WEBMD_STAGE;
CREATE OR REPLACE STAGE raw.YOUTUBE_STAGE;
-- CREATE OR REPLACE STAGE adtech_analytics_devraw.SHARETHROUGH_STAGE;
create or replace pipe CM360_PIPE auto_ingest=TRUE as COPY INTO CM360_raw_data FROM @CM360_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe AMAZON_PIPE auto_ingest=TRUE as COPY INTO Amazon_raw_data FROM @Amazon_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe AVZU_PIPE auto_ingest=TRUE as COPY INTO AVZU_raw_data FROM @AVZU_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe BINGADS_PIPE auto_ingest=TRUE as COPY INTO BingAds_raw_data FROM @BingAds_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

 CREATE or replace pipe CM360_PIPE auto_ingest=true as COPY INTO adtech_analytics_dev.RAW.cm360_raw_data
  FROM @adtech_analytics_devraw.cm360_stage
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';
  
create or replace pipe CRITEO_PIPE auto_ingest=TRUE as COPY INTO Criteo_raw_data FROM @Criteo_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

 CREATE or replace pipe DV360_PIPE auto_ingest=true as COPY INTO DV360_raw_data
FROM @DV360_stage
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR = 'CONTINUE';

create or replace pipe HINDHU_PIPE auto_ingest=TRUE as COPY INTO Hindhu_raw_data FROM @Hindhu_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

 CREATE or replace pipe IAS_PIPE auto_ingest=true as COPY INTO RAW.IAS_RAW_DATA
FROM @raw.ias_stage
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe INMOBI_PIPE auto_ingest=TRUE as COPY INTO InMobi_raw_data FROM @InMobi_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe MAGNITE_PIPE auto_ingest=TRUE as COPY INTO Magnite_raw_data FROM @Magnite_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe MIQ_PIPE auto_ingest=TRUE as COPY INTO MIQ_raw_data FROM @MIQ_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe PUBMATIC_PIPE auto_ingest=TRUE as COPY INTO PubMatic_raw_data FROM @PubMatic_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe REMEZCLA_PIPE auto_ingest=TRUE as COPY INTO remezcla_raw_data FROM @remezcla_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe SHARETHROUGH_PIPE auto_ingest=TRUE as COPY INTO Sharethrough_raw_data FROM @sharethrough_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe TOI_PIPE auto_ingest=TRUE as COPY INTO TOI_raw_data FROM @TOI_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe TTD_PIPE auto_ingest=TRUE as COPY INTO TTD_raw_data FROM @TTD_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe WEBMD_PIPE auto_ingest=TRUE as COPY INTO WebMD_raw_data FROM @WebMD_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';

create or replace pipe YOUTUBE_PIPE auto_ingest=TRUE as COPY INTO Youtube_raw_data FROM @Youtube_stage FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1) ON_ERROR='CONTINUE';
